import localFont from 'next/font/local'
import "./globals.css";
import Footer from './components/Footer';
import Navbar from './components/Navbar';
import LenisProvider from './components/LenisProvider';

const PPNeueMachina = localFont({
  src: [
    {
      path: './assets/fonts/PPNeueMachina-InktrapLight.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: './assets/fonts/PPNeueMachina-InktrapRegular.ttf',
      weight: '600',
      style: 'normal'
    },
    {
      path: './assets/fonts/PPNeueMachina-InktrapMedium.ttf',
      weight: '700',
      style: 'normal'
    }
  ],
  display: 'swap',
  variable: '--font-pp-neue-machina'
});

const SaolStandard = localFont({
  src: './assets/fonts/SaolStandard-LightItalic.otf',
  display: 'swap',
  variable: '--font-saol-standard'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${PPNeueMachina.variable} ${SaolStandard.variable} antialiased overflow-x-hidden bg-white`}
      >	
        <LenisProvider>
          <Navbar />
            {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
